apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istiocontrolplane
spec:
  hub: docker.io/istio
  components:
    base:
      enabled: true
#    pilot:
#      enabled: true
#      k8s:
#        service:
#          type: LoadBalancer
#        service_annotations:
#          cloud.google.com/load-balancer-type: Internal
