apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istiocontrolplane
spec:
  hub: docker.io/istio
  components:
    base:
      enabled: true
    # To reproduce the issue, uncomment the following section.
    pilot:
      enabled: true
      k8s:
        service:
          type: LoadBalancer
        serviceAnnotations:
          cloud.google.com/load-balancer-type: Internal
